version: 4.2
os: linux
files:
  - source: /
    destination: /data/app/app.templateapiserver1.0.1/
permissions:
  - object: /data/app/app.templateapiserver1.0.1/
    owner: admin
    group: admin
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure.sh
      timeout: 300
      runas: admin
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: admin
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: admin
