version: 4.2
os: linux
files:
  - source: /ios/tongshiwo_*.ipa
    destination: /home/ubuntu/tongshiwo/appupdate
  - source: /ios/tongshiwoplist.plist
    destination: /home/ubuntu/tongshiwo/appupdate
  - source: /ios/www.zip
    destination: /usr/share/tomcat8-codedeploy/webapps/
  - source: /
    destination: /opt/fit2cloud-demo/
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
